### ISSUE TITLE
Token-Agnostic Sends

### ISSUE THREAD

**Issue by AdamBLevine** [loon3/LTB-Companion#1]
On Inventory Page:

Toggle ability for each token to make it available or unavailable as an option on the Wallet page.

On Wallet Page:

You'd click the balance and it would drop-down into a list of your other balances that are not deselected in your inventory.

Whatever balance is showing on your wallet page would be the token and balance you are controlling with that page to send.

Balances and sends are specific to the address that is being controlled from the dropdown above, so multiple addresses would not pool tokens since that would require multiple sends and is more complicated.

**Comment by loon3** [comment]
Integrated asset/token switching with the latest commit.  From Token Inventory, you can select "Send" from each token which will redirect to your wallet with that specific token balance displayed.

**Comment by AdamBLevine** [comment]
I like it.
